[{"ContainerToolsException.Message":"Avec Visual Studio Container Tools, Docker doit être exécuté avant la génération, le débogage ou l'exécution d'un projet conteneurisé.  Pour plus d'informations, consultez : https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [22296] Failed to execute script docker-compose\r\n   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   à Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() dans D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:ligne 253\r\n--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---\r\n   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   à Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() dans D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:ligne 104\r\n--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---\r\n   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   à Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() dans D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:ligne 418\r\n--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---\r\n   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   à Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__38.MoveNext() dans D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:ligne 87\r\nCode d'erreur : DT1001\r\nGravité : Error\r\nLigne de commande : docker-compose  -f \"E:\\learning\\mymicroservicess\\src\\docker-compose.yml\" -f \"E:\\learning\\mymicroservicess\\src\\docker-compose.override.yml\" -f \"E:\\learning\\mymicroservicess\\src\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose2392874158034891523 --ansi never kill\r\nCode de sortie de la commande : -1\r\nSortie de la commande : \r\nErreur de commande : Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'Le fichier spÚcifiÚ est introuvable.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'Le fichier spÚcifiÚ est introuvable.')\r\n[22296] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"Avec Visual Studio Container Tools, Docker doit être exécuté avant la génération, le débogage ou l'exécution d'un projet conteneurisé.  Pour plus d'informations, consultez : https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [3700] Failed to execute script docker-compose\r\n   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   à Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() dans D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:ligne 253\r\n--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---\r\n   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   à Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() dans D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:ligne 104\r\n--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---\r\n   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   à Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() dans D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:ligne 418\r\n--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---\r\n   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   à Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__38.MoveNext() dans D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:ligne 87\r\nCode d'erreur : DT1001\r\nGravité : Error\r\nLigne de commande : docker-compose  -f \"E:\\learning\\mymicroservicess\\src\\docker-compose.yml\" -f \"E:\\learning\\mymicroservicess\\src\\docker-compose.override.yml\" -f \"E:\\learning\\mymicroservicess\\src\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose2392874158034891523 --ansi never kill\r\nCode de sortie de la commande : -1\r\nSortie de la commande : \r\nErreur de commande : Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'Le fichier spÚcifiÚ est introuvable.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'Le fichier spÚcifiÚ est introuvable.')\r\n[3700] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"Avec Visual Studio Container Tools, Docker doit être exécuté avant la génération, le débogage ou l'exécution d'un projet conteneurisé.  Pour plus d'informations, consultez : https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [6260] Failed to execute script docker-compose\r\n   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   à Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() dans D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:ligne 253\r\n--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---\r\n   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   à Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() dans D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:ligne 104\r\n--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---\r\n   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   à Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() dans D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:ligne 418\r\n--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---\r\n   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   à Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__38.MoveNext() dans D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:ligne 87\r\nCode d'erreur : DT1001\r\nGravité : Error\r\nLigne de commande : docker-compose  -f \"E:\\learning\\mymicroservicess\\src\\docker-compose.yml\" -f \"E:\\learning\\mymicroservicess\\src\\docker-compose.override.yml\" -f \"E:\\learning\\mymicroservicess\\src\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose2392874158034891523 --ansi never kill\r\nCode de sortie de la commande : -1\r\nSortie de la commande : \r\nErreur de commande : Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'Le fichier spÚcifiÚ est introuvable.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'Le fichier spÚcifiÚ est introuvable.')\r\n[6260] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"Avec Visual Studio Container Tools, Docker doit être exécuté avant la génération, le débogage ou l'exécution d'un projet conteneurisé.  Pour plus d'informations, consultez : https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [9992] Failed to execute script docker-compose\r\n   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   à Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() dans D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:ligne 253\r\n--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---\r\n   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   à Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() dans D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:ligne 104\r\n--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---\r\n   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   à Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() dans D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:ligne 418\r\n--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---\r\n   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   à Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__38.MoveNext() dans D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:ligne 87\r\nCode d'erreur : DT1001\r\nGravité : Error\r\nLigne de commande : docker-compose  -f \"E:\\learning\\mymicroservicess\\src\\docker-compose.yml\" -f \"E:\\learning\\mymicroservicess\\src\\docker-compose.override.yml\" -f \"E:\\learning\\mymicroservicess\\src\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose2392874158034891523 --ansi never kill\r\nCode de sortie de la commande : -1\r\nSortie de la commande : \r\nErreur de commande : Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'Le fichier spÚcifiÚ est introuvable.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'Le fichier spÚcifiÚ est introuvable.')\r\n[9992] Failed to execute script docker-compose\r\n"},{"ContainerToolsException.Message":"Avec Visual Studio Container Tools, Docker doit être exécuté avant la génération, le débogage ou l'exécution d'un projet conteneurisé.  Pour plus d'informations, consultez : https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [14980] Failed to execute script docker-compose\r\n   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   à Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() dans D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:ligne 253\r\n--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---\r\n   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   à Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() dans D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:ligne 104\r\n--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---\r\n   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   à Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() dans D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:ligne 418\r\n--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---\r\n   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   à Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__38.MoveNext() dans D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:ligne 87\r\nCode d'erreur : DT1001\r\nGravité : Error\r\nLigne de commande : docker-compose  -f \"E:\\learning\\mymicroservicess\\src\\docker-compose.yml\" -f \"E:\\learning\\mymicroservicess\\src\\docker-compose.override.yml\" -f \"E:\\learning\\mymicroservicess\\src\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose2392874158034891523 --ansi never kill\r\nCode de sortie de la commande : -1\r\nSortie de la commande : \r\nErreur de commande : Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', 'Le fichier spÚcifiÚ est introuvable.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'Le fichier spÚcifiÚ est introuvable.')\r\n[14980] Failed to execute script docker-compose\r\n"}]